Repository kyan/jukebox-js, pull requests merged in 2019-11, with the labels that each got.

#79 Google Login and much more
  .github/workflows/nodejs.yml
  README.md
  backend/package-lock.json
  backend/package.json
  backend/src/app.js
  backend/src/lib/broadcaster/index.js
  backend/src/lib/broadcaster/index.spec.js
  backend/src/lib/constants/auth.js
  backend/src/lib/event-logger/index.js
  backend/src/lib/event-logger/index.spec.js
  backend/src/lib/handlers/authenticate/index.js
  backend/src/lib/handlers/authenticate/index.spec.js
  backend/src/lib/handlers/error/index.js
  backend/src/lib/handlers/handshake/index.js
  backend/src/lib/handlers/handshake/index.spec.js
  backend/src/lib/local-storage/index.js
  backend/src/lib/local-storage/index.spec.js
  backend/src/lib/message-triage/index.js
  backend/src/lib/message-triage/index.spec.js
  backend/src/lib/services/mongodb/index.js
  backend/src/lib/services/mongodb/models/event/index.js
  backend/src/lib/services/mongodb/models/user/index.js
  backend/src/lib/services/mongodb/models/user/index.spec.js
  backend/src/lib/services/mopidy/index.js
  backend/src/lib/services/mopidy/index.spec.js
  backend/src/lib/transformer/index.js
  backend/src/lib/transformer/index.spec.js
  db-seed/Dockerfile
  db-seed/seed.sh
  db-seed/users.json
  docker-compose.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/__snapshots__/app.spec.js.snap
  frontend/src/actions/index.js
  frontend/src/actions/index.spec.js
  frontend/src/app.spec.js
  frontend/src/components/controls/__snapshots__/index.spec.js.snap
  frontend/src/components/controls/index.js
  frontend/src/components/controls/index.spec.js
  frontend/src/components/settings/__snapshots__/index.spec.js.snap
  frontend/src/components/settings/index.js
  frontend/src/components/settings/index.spec.js
  frontend/src/constants/auth-api.js
  frontend/src/constants/index.js
  frontend/src/containers/dashboard/__snapshots__/index.spec.js.snap
  frontend/src/containers/dashboard/index.js
  frontend/src/containers/dashboard/index.spec.js
  frontend/src/containers/settings/__snapshots__/index.spec.js.snap
  frontend/src/containers/settings/index.js
  frontend/src/containers/settings/index.spec.js
  frontend/src/contexts/google.js
  frontend/src/reducers/jukebox/__snapshots__/index.spec.js.snap
  frontend/src/reducers/jukebox/index.js
  frontend/src/reducers/jukebox/index.spec.js
  frontend/src/reducers/settings/index.js
  frontend/src/reducers/settings/index.spec.js
  frontend/src/utils/on-message-handler/index.js
  frontend/src/utils/on-message-handler/index.spec.js
Labels: enhancement

#84 Auto stop the jukebox
  backend/package-lock.json
  backend/package.json
  backend/src/app.js
  backend/src/lib/scheduler/index.js
  backend/src/lib/scheduler/index.spec.js
Labels: Needs Review

#85 Update NPMs
  backend/package-lock.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/__snapshots__/app.spec.js.snap
  frontend/src/components/radio-stream/__snapshots__/index.spec.js.snap
  frontend/src/components/radio-stream/index.js
  frontend/src/components/radio-stream/index.spec.js
  frontend/src/components/settings/__snapshots__/index.spec.js.snap
  frontend/src/containers/dashboard/__snapshots__/index.spec.js.snap
Labels: Needs Review

#86 Time remaining and code cleanup
  backend/src/app.js
  backend/src/lib/services/mopidy/index.js
  backend/src/lib/services/mopidy/index.spec.js
  frontend/package.json
  frontend/src/components/current-track/__snapshots__/index.spec.js.snap
  frontend/src/components/current-track/index.css
  frontend/src/components/current-track/index.js
  frontend/src/containers/current-track-container/index.js
  frontend/src/containers/jukebox-middleware/index.js
  frontend/src/containers/jukebox-middleware/index.spec.js
  frontend/src/reducers/assets/index.js
  frontend/src/reducers/timer/index.js
  frontend/src/reducers/timer/index.spec.js
  frontend/src/utils/time/index.js
Labels: Needs Review

#92 Unify event handling between client, api and mopidy
  backend/package-lock.json
  backend/package.json
  backend/src/app.js
  backend/src/lib/handlers/mopidy/index.js
  backend/src/lib/local-storage/index.spec.js
  backend/src/lib/payload/index.js
  backend/src/lib/services/mopidy/index.js
  backend/src/lib/services/mopidy/index.spec.js
  backend/src/lib/str-to-function/index.js
  backend/src/lib/str-to-function/index.spec.js
  backend/src/lib/transformer/index.js
  backend/src/lib/transformer/index.spec.js
  frontend/src/actions/index.js
  frontend/src/actions/index.spec.js
  frontend/src/components/controls/__snapshots__/index.spec.js.snap
  frontend/src/components/controls/index.js
  frontend/src/components/controls/index.spec.js
  frontend/src/constants/index.js
  frontend/src/containers/dashboard/__snapshots__/index.spec.js.snap
  frontend/src/containers/dashboard/index.js
  frontend/src/containers/dashboard/index.spec.js
  frontend/src/containers/jukebox-middleware/index.js
  frontend/src/containers/jukebox-middleware/index.spec.js
  frontend/src/reducers/assets/index.js
  frontend/src/reducers/assets/index.spec.js
  frontend/src/reducers/jukebox/__snapshots__/index.spec.js.snap
  frontend/src/reducers/jukebox/index.js
  frontend/src/reducers/jukebox/index.spec.js
  frontend/src/utils/on-message-handler/index.js
  frontend/src/utils/time/index.js
  frontend/src/utils/time/index.spec.js
  scripts/tests.sh
Labels: Needs Review, enhancement

#96 Updates readme to include more detailed env setup instructions for dev
  README.md
Labels: enhancement

#97 Post new Jukebox info to now playing
  .env.example
  README.md
  backend/src/lib/handlers/now-playing/index.js
  backend/src/lib/handlers/now-playing/index.spec.js
  backend/src/lib/services/http/index.js
  backend/src/lib/services/http/index.spec.js
  backend/src/lib/transformer/index.js
  backend/src/lib/transformer/index.spec.js
  docker-compose.yml
Labels: enhancement

#102 Adds base docker setup for local mopidy
  .env.example
  README.md
  docker-compose-mopidy.yml
  docker-compose.yml
  docs/mopidy_docker.md
  makefile
  mopidy/Dockerfile
  mopidy/config/mopidy.conf
  mopidy/config/pulse-client.conf
  mopidy/entrypoint.sh
Labels: In Progress, enhancement
