Repository kyan/jukebox-js, pull requests merged in 2019-12, with the labels that each got.

#99 Fixes Google JWT token not being refreshed when tab hidden
  frontend/package-lock.json
  frontend/package.json
  frontend/src/containers/dashboard/index.js
  frontend/src/containers/dashboard/index.spec.js
  frontend/src/reducers/settings/index.js
  frontend/src/reducers/settings/index.spec.js
  frontend/src/setupTests.js
  frontend/src/utils/signin-token/index.js
  frontend/src/utils/signin-token/index.spec.js
Labels: Needs Review

#105 Use .env for mopidy config
  .env.example
  .gitignore
  docker-compose-mopidy.yml
  docs/mopidy_docker.md
  makefile
  mopidy/config/mopidy.conf
  mopidy/entrypoint.sh
Labels: Needs Review

#106 Various amends to aid future front end development
  .gitignore
  docker-compose.yml
  frontend/jsconfig.json
  frontend/src/App.js
  frontend/src/__snapshots__/app.spec.js.snap
  frontend/src/actions/index.js
  frontend/src/actions/index.spec.js
  frontend/src/components/controls/index.js
  frontend/src/components/controls/index.spec.js
  frontend/src/components/current-track/index.js
  frontend/src/components/current-track/index.spec.js
  frontend/src/components/drag-in-track/index.js
  frontend/src/components/settings/index.css
  frontend/src/components/settings/index.js
  frontend/src/components/settings/index.spec.js
  frontend/src/components/tracklist/index.js
  frontend/src/components/tracklist/index.spec.js
  frontend/src/constants/common.js
  frontend/src/containers/current-track-container/index.js
  frontend/src/containers/dashboard-container/__snapshots__/index.spec.js.snap
  frontend/src/containers/dashboard-container/index.js
  frontend/src/containers/dashboard-container/index.spec.js
  frontend/src/containers/dashboard/__snapshots__/index.spec.js.snap
  frontend/src/containers/dashboard/index.js
  frontend/src/containers/jukebox-middleware/index.js
  frontend/src/containers/jukebox-middleware/index.spec.js
  frontend/src/index.css
  frontend/src/reducers/assets/index.js
  frontend/src/reducers/assets/index.spec.js
  frontend/src/reducers/jukebox/index.js
  frontend/src/reducers/jukebox/index.spec.js
  frontend/src/reducers/settings/index.js
  frontend/src/reducers/settings/index.spec.js
  frontend/src/reducers/timer/index.js
  frontend/src/reducers/timer/index.spec.js
  frontend/src/reducers/track/index.js
  frontend/src/reducers/track/index.spec.js
  frontend/src/reducers/tracklist/index.js
  frontend/src/reducers/tracklist/index.spec.js
  frontend/src/selectors/index.js
  frontend/src/utils/on-message-handler/index.js
  frontend/src/utils/on-message-handler/index.spec.js
  frontend/src/utils/state/index.js
  frontend/src/views/dashboard/__snapshots__/index.spec.js.snap
  frontend/src/views/dashboard/index.css
  frontend/src/views/dashboard/index.js
  frontend/src/views/dashboard/index.spec.js
Labels: Needs Review, enhancement

#108 Split Transform so it handles mopidy core messages separately.
  backend/src/app.js
  backend/src/constants/message.js
  backend/src/constants/mopidy.js
  backend/src/handlers/mopidy/index.js
  backend/src/services/mopidy/index.js
  backend/src/services/mopidy/index.spec.js
  backend/src/utils/broadcaster/index.js
  backend/src/utils/broadcaster/index.spec.js
  backend/src/utils/transformer/index.js
  backend/src/utils/transformer/index.spec.js
  backend/src/utils/transformer/transformers/mopidy/tracklist/index.js
Labels: enhancement

#111 Bit of refactoring replacing some callbacks with Promises and some other bits and pieces
  backend/src/constants/mopidy.js
  backend/src/handlers/mopidy/image-cache/index.js
  backend/src/handlers/mopidy/image-cache/index.spec.js
  backend/src/handlers/mopidy/index.js
  backend/src/handlers/mopidy/index.spec.js
  backend/src/services/spotify/index.js
  backend/src/services/spotify/index.spec.js
  backend/src/utils/broadcaster/index.js
  backend/src/utils/broadcaster/index.spec.js
  backend/src/utils/payload/index.js
  backend/src/utils/transformer/index.js
  frontend/src/constants/mopidy-api.js
  frontend/src/utils/notify/__snapshots__/index.spec.js.snap
  frontend/src/utils/notify/index.js
  frontend/src/utils/notify/index.spec.js
  frontend/src/utils/on-message-handler/index.js
  frontend/src/utils/on-message-handler/index.spec.js
Labels: Needs Review, enhancement

#113 Promisify transformer
  backend/src/services/mopidy/index.js
  backend/src/services/mopidy/index.spec.js
  backend/src/utils/broadcaster/index.js
  backend/src/utils/broadcaster/index.spec.js
  backend/src/utils/transformer/index.js
  backend/src/utils/transformer/index.spec.js
Labels: In Progress, Needs Review

#115 Implements Spotify search
  backend/src/__mockData__/searchResults.json
  backend/src/app.js
  backend/src/constants/message.js
  backend/src/constants/mopidy.js
  backend/src/constants/search.js
  backend/src/handlers/mopidy/index.spec.js
  backend/src/handlers/search/index.js
  backend/src/handlers/search/index.spec.js
  backend/src/services/spotify/index.js
  backend/src/services/spotify/index.spec.js
  backend/src/utils/broadcaster/index.js
  backend/src/utils/broadcaster/index.spec.js
  backend/src/utils/message-triage/index.js
  backend/src/utils/message-triage/index.spec.js
  backend/src/utils/transformer/index.js
  backend/src/utils/transformer/index.spec.js
  backend/src/utils/transformer/transformers/mopidy/track/index.js
  backend/src/utils/transformer/transformers/spotify/search/index.js
  backend/src/utils/transformer/transformers/spotify/search/index.spec.js
  frontend/package.json
  frontend/src/components/controls/index.js
  frontend/src/containers/dashboard-container/__snapshots__/index.spec.js.snap
  frontend/src/containers/dashboard-container/index.js
  frontend/src/containers/dashboard-container/index.spec.js
  frontend/src/containers/jukebox-middleware/index.js
  frontend/src/containers/jukebox-middleware/index.spec.js
  frontend/src/dashboard/__snapshots__/index.spec.js.snap
  frontend/src/dashboard/index.css
  frontend/src/dashboard/index.js
  frontend/src/dashboard/index.spec.js
  frontend/src/index.css
  frontend/src/reducers/index.js
  frontend/src/search/__snapshots__/index.spec.js.snap
  frontend/src/search/actions/index.js
  frontend/src/search/actions/index.spec.js
  frontend/src/search/components/button/index.js
  frontend/src/search/components/sidebar/__snapshots__/index.spec.js.snap
  frontend/src/search/components/sidebar/index.css
  frontend/src/search/components/sidebar/index.js
  frontend/src/search/components/sidebar/index.spec.js
  frontend/src/search/constants.js
  frontend/src/search/index.js
  frontend/src/search/index.spec.js
  frontend/src/search/reducers/index.js
  frontend/src/search/reducers/index.spec.js
  frontend/src/utils/on-message-handler/index.js
  frontend/src/utils/on-message-handler/index.spec.js
  frontend/src/views/dashboard/__snapshots__/index.spec.js.snap
  frontend/src/views/dashboard/index.css
  frontend/src/views/dashboard/index.js
Labels: Needs Review, enhancement

#116 Remove triage and promisify Auth handler
  backend/src/app.js
  backend/src/handlers/authenticate/index.js
  backend/src/handlers/authenticate/index.spec.js
  backend/src/utils/message-triage/index.js
  backend/src/utils/message-triage/index.spec.js
Labels: enhancement

#114 [#89] Store data about who has added a track to the JB
  backend/src/handlers/mopidy/index.js
  backend/src/services/mongodb/models/track/index.js
  backend/src/services/mongodb/models/track/index.spec.js
  backend/src/utils/track/index.js
  backend/src/utils/track/index.spec.js
  backend/src/utils/transformer/index.js
  backend/src/utils/transformer/index.spec.js
  backend/src/utils/transformer/transformers/mopidy/track/index.js
  backend/src/utils/transformer/transformers/mopidy/tracklist/index.js
  backend/src/utils/transformer/transformers/mopidy/tracklist/index.spec.js
  frontend/src/__mockData__/api/index.js
  frontend/src/components/tracklist/__snapshots__/index.spec.js.snap
  frontend/src/components/tracklist/added-by/__snapshots__/index.spec.js.snap
  frontend/src/components/tracklist/added-by/index.js
  frontend/src/components/tracklist/added-by/index.spec.js
  frontend/src/components/tracklist/index.css
  frontend/src/components/tracklist/index.js
Labels: Needs Review, enhancement

#118 Some tweaks to addedBy
  backend/package.json
  backend/src/handlers/authenticate/index.js
  backend/src/handlers/mopidy/index.js
  backend/src/services/mongodb/models/user/index.js
  backend/src/services/mopidy/index.js
  backend/src/services/mopidy/index.spec.js
  backend/src/services/spotify/index.js
  backend/src/services/spotify/index.spec.js
  backend/src/utils/broadcaster/index.js
  backend/src/utils/broadcaster/index.spec.js
  backend/src/utils/track/index.js
  backend/src/utils/track/index.spec.js
  backend/src/utils/transformer/index.js
  backend/src/utils/transformer/index.spec.js
  backend/src/utils/transformer/transformers/mopidy/track/index.spec.js
  backend/src/utils/transformer/transformers/mopidy/tracklist/index.js
  backend/src/utils/transformer/transformers/mopidy/tracklist/index.spec.js
  frontend/src/components/tracklist/added-by/__snapshots__/index.spec.js.snap
  frontend/src/components/tracklist/added-by/index.js
  frontend/src/components/tracklist/added-by/index.spec.js
  frontend/src/components/tracklist/index.css
  frontend/src/constants/mopidy-api.js
Labels: enhancement

#119 Make sure we add the tracks in mongo first
  backend/src/services/spotify/index.js
  backend/src/services/spotify/index.spec.js
  backend/src/utils/track/index.js
  backend/src/utils/track/index.spec.js
  backend/src/utils/transformer/index.js
Labels: enhancement
